### PR TITLE
Initial implementation of typesOnly mode.

### PR DESCRIPTION
**Pull request by mattvagni**
Context: https://github.com/segmentio/typewriter/issues/120

Opening this early to discuss approach @colinking 

### Approach
I originally started by trying to generate some additional types in the pre-existing `segment.ts` to add additional overloads for `track()`. 

This didn't work out though 😢and would have been my preferred approach: 

Currently `typewriter` + typescript requires people install `@types/segment-analytics`. This includes a very loose [definition of track](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/segment-analytics/index.d.ts#L111-L115) and a global definition of [analytics](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/segment-analytics/index.d.ts#L209). As far as I could tell from numerous typescript Github issues it's impossible to undo global type definitions, you can only add to them using overloads. 

This means that even if we generate the correct types from our tracking plan you are still able to track anything due to these loose fallbacks in `@types/segment-analytics`.

**To fix this**, I instead went down a different route of replacing `@types/segment-analytics` entirely. The idea here being that when you use typewriter in this new typesOnly mode you **don't** have to install `@types/segment-analytics` but instead get a custom version to fit your tracking plan. This solves the above problem and is quite tidy in my opinion. However, it does increase the maintenance burden since now some of the global types like on identify are in two places.

### Naming
`typesOnly` is not great since the types it generates are fundamentally different than when you output the TS as well. Maybe `typeDefinitionsOnly` ?

### CODE REVIEW

**Comment by colinking** [comment]
Neat, this is looking great so far @mattvagni 🙌 

Were you able to test this out with your team's Tracking Plan to see how well TS worked with these declarations?

It may also help to add an e2e test, which you could do by forking the `web-typescript` one here: https://github.com/segmentio/typewriter/tree/master/tests/e2e/web-typescript And then updating the callsites from generated functions -> track calls. Doesn't necessarily need to pass right away, but would make it easy to review the generation logic :)

**Comment by mattvagni** [comment]
Thanks @colinking 🙏 

When running the `e2e` tests however (even in master) I get:

> Uncaught SyntaxError: Octal escape sequences are not allowed in strict mode.

Screenshot 2020-03-01 at 16 38 47

Any ideas what this might be?

**Comment by colinking** [comment]
Hmm, this is a new one.

- You're on macOS, right?
- Is this error specific to the `web-javascript` e2e test? Do any of the other `make test-*` commands work? https://github.com/segmentio/typewriter/blob/c005808eeba77927d35ee3b423a6402bb6bf8d5a/Makefile#L44-L57

**Comment by mattvagni** [comment]
Sorry for the radio silence. Due to covid I'm focusing on internal work at the moment to deal with the upsurge in demand we're experiencing. I won't be able to get back to this for quite some time. If you are able to take this over in the meantime that would be much appreciated. Otherwise I can get back to it in a few months time!

Thanks

**Comment by colinking** [comment]
All good, @mattvagni -- best of luck with your work with COVID :)

**Comment by mattvagni** [comment]
Apoligies - I've since moved company and are no longer (or not yet rather) using Segment. Will close this for now!

**Pull request closed without merging**
